#!/bin/sh /etc/rc.common

# part of the clarissa project
# https://gitlab.com/evils/clarissa

START=32
STOP=16

USE_PROCD=1

start_service()
{
	. "${IPKG_INSTROOT}/lib/functions/network.sh"

	if network_get_device dev lan; then
		procd_open_instance
		procd_set_param command /usr/bin/clarissa
		procd_append_param command -I "$dev"
		procd_set_param respawn
		procd_close_instance
	else
		echo "Unable to determine LAN interface" >&2
	fi
}
