.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2019 Evils <evils.devils@protonmail.com>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH CLARISSA 8 "2019-05-12"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
Clarissa \- near real-time network census daemon
.SH SYNOPSIS
.B clarissa
.RI [ options ]
.br
.SH DESCRIPTION
.B Clarissa
is a daemon which keeps a list of all connected MAC addresses on a network.
.br
It can keep this with sub-second resolution and can monitor passively.
.br
It currently includes 
.B clar_count
a utility to report a count of known and unknown addresses.
.PP
.SH OPTIONS
Defaults: Interface = first, Timeout = 2s, Nags = 3, interval = Timeout / Nags, Promiscuous = 0, Verbosity = 0, subnet = interface's IPv4 subnet, output file = /tmp/clarissa_list, Output interval = timeout * ϕ
.br

.TP
.B --help or -h
show the help message
.TP
.B --header or -H
show the Header and exit
.TP
.B --verbose or -v
increase Verbosity
.br
(shows 0 = err & warn < MAC < IP < chatty < debug < vomit)
.TP
.B --quiet or -q
Quiet, send out no packets (equivalent to -n 0)
.TP
.B --promiscuous or -p
set the interface to Promiscuous mode
.SH
Requiring an argument:
.BR
.TP
.B --interface or -I
set the Interface used (one per instance)
.TP
.B --interval or -i
set the interval (in milliseconds)
.TP
.B --nags or -n
set the number of times to "Nag" a target
.TP
.B --timeout or -t
set the Timeout for an entry (wait time for nags in ms)
.TP
.B --subnet or -s
get a Subnet to filter by (in CIDR notation)
.TP
.B --file or -f
File input (pcap file, also works with - (stdin))
.TP
.B --output_file or -o
set the output filename
.TP
.B --output_interval or -O
set the file Output interval
.SH SEE ALSO
.BR clar_count (1)
.br

https://gitlab.com/evils/clarissa
