= clarissa-count(1)
include::meta.adoc[]
:doctype: manpage

== Name
clarissa-count - Utility for counting known and unknown MAC addresses in clarissa's output.

== Synopsis
*clarissa count* [path to macs.csv] [path to Clarissa's list] [-ctijnal | -nj]

== Description
*clarissa count* is a utility intended to count known and unknown MAC addresses from a macs.csv file, in *clarissa*'s output. +
It can output in a variety of formats specified by the option used.

== Options
*clarissa count* only takes 1 option, this is required. +
These control it's output format. +
Several can be parsed by *Telegraf* for use with *InfluxDB*. +

[%hardbreaks]
    Long      Short
--csv          -c
   CSV with a header line (works with *Telegraf*)
--title        -t
   One-line CSV containing the count of known addresses and of everything else.
--json         -j
   JSON object (works with *Telegraf*)
--influx       -i
   influx line protocol (works with *Telegraf* and presumably *InfluxDB*)
--names        -n
   list of names, one per line
--names_json   -nj
   same content as -n but in a JSON array
--log [salt]   -l [salt]
   Keep a hashed and salted log of unique addresses seen in the user's home directory.
   Unless a salt is supplied, a random salt will be used per  instance.

== macs.csv format
MAC address,name +
MAC address,!name +
MAC address,name? +
MAC address,!name? +

Any lines without a MAC address won't get used and any fields after the name will be ignored.
Any name with an exclamation mark !  will not be output,
and any name containing a question mark ?  will not be counted.

== See Also
*clarissa*(8), *socat*(1), *cat*(1) +
{url-project}
