#pragma once

// version of the clarissa binary
#define VERSION "v1.0"

// this is the version of the format generated by asprint_clar()
#define FORMAT_VERSION "v1.0"

// output path where the socket is found
#define PATH "/var/run/clar"

// asprintf() galore
#define _GNU_SOURCE

// required capture length to get MAC and IPv[4|6] from all supported frames
#define CAPLEN 74

// number of things in the poll
#define POLL_N 2

// more defaults at main:handle_opts()
// these are reused outside of that
#define DEFAULT_NAGS 4
#define DEFAULT_TIMEOUT 5000

// ethernet types
#define IPv4 0x0800
#define IPv6 0x86DD
#define ARP 0x0806
#define DOT1Q 0x8100
#define DOT1AD 0X88A8
#define DOT1QINQ 0x9100
#define ETH_SIZE 0x0600
#define ARUBA_AP_BC 0x8ffd
#define EAPOL 0x888e
#define DOT11R 0x890d
